name: Send Email

on:
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Send invoice report email
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          SEDAPAL_EMAIL: ${{ secrets.SEDAPAL_EMAIL }}
          SEDAPAL_PASSWORD: ${{ secrets.SEDAPAL_PASSWORD }}
          LUZDELSUR_EMAIL: ${{ secrets.LUZDELSUR_EMAIL }}
          LUZDELSUR_PASSWORD: ${{ secrets.LUZDELSUR_PASSWORD }}
          CALIDDA_EMAIL: ${{ secrets.CALIDDA_EMAIL }}
          CALIDDA_PASSWORD: ${{ secrets.CALIDDA_PASSWORD }}
        run: bun src/scripts/send-email.ts
